name: Crccare Deployment

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.2"

      - name: Install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          source ~/.bashrc
          nvm install 16
          nvm use 16

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          composer dump-autoload
          php artisan config:clear
          npm run dev

      - name: Copy Environment File
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/staging" ]; then
            cp .env.staging .env
          elif [ "${GITHUB_REF}" == "refs/heads/master" ]; then
            cp .env.example .env
          fi

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          sshpass -p 'SZ3bLYhBSC9scTp' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ bintangtobing@153.92.5.213:/home/bintangtobing/crccaredev.bintangtobing.com/
          sshpass -p 'SZ3bLYhBSC9scTp' ssh -o StrictHostKeyChecking=no bintangtobing@153.92.5.213 'cd /home/bintangtobing/crccaredev.bintangtobing.com && php artisan key:generate --ansi && php artisan migrate --force && php artisan optimize:clear && php artisan storage:link && php artisan config:clear'

      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        run: |
          sshpass -p 'SZ3bLYhBSC9scTp' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ bintangtobing@153.92.5.213:/home/bintangtobing/crccaredev.bintangtobing.com/
          sshpass -p 'SZ3bLYhBSC9scTp' ssh -o StrictHostKeyChecking=no bintangtobing@153.92.5.213 'cd /home/bintangtobing/crccaredev.bintangtobing.com && php artisan key:generate --ansi && php artisan migrate --force && php artisan optimize:clear && php artisan storage:link && php artisan config:clear'
